// import Navbar from "#components/Navbar.jsx";
// import Welcome from "#components/Welcome.jsx";
// import Dock from "#components/Dock.jsx";
// export {Navbar,Welcome,Dock};
export { default as Navbar } from "./Navbar.jsx";
export { default as Welcome } from "./Welcome.jsx";
export { default as Dock } from "./Dock.jsx";
export { default as Finder } from "./Finder.jsx";
export { default as Safari } from "./Safari.jsx";
export { default as Photos } from "./Photos.jsx";
export { default as Terminal } from "./Terminal.jsx";
export { default as Contact } from "./Contact.jsx";
