// import Navbar from "#components/Navbar.jsx";
// import Welcome from "#components/Welcome.jsx";
// import Dock from "#components/Dock.jsx";
// export {Navbar,Welcome,Dock};
export { default as Navbar } from "./Navbar.jsx";
export { default as Welcome } from "./Welcome.jsx";
export { default as Dock } from "./Dock.jsx";
export { default as Finder } from "./Finder.jsx";
export { default as Safari } from "./Safari.jsx";
export { default as Photos } from "./Photos.jsx";
export { default as Terminal } from "./Terminal.jsx";
export { default as Contact } from "./Contact.jsx";
export { default as Launchpad } from "./Launchpad.jsx";
export { default as Spotlight } from "./Spotlight.jsx";
export { default as LockScreen } from "./LockScreen.jsx";
export { default as AppleMenu } from "./AppleMenu.jsx";
export { default as Bear } from "./Bear.jsx";
export { default as KashviGPT } from "./KashviGPT.jsx";
export { default as DesktopHints } from "./DesktopHints.jsx";
export { default as BootScreen } from "./BootScreen.jsx";
export { default as AboutMac } from "./AboutMac.jsx";
export { default as SystemSettings } from "./SystemSettings.jsx";
export { default as AppStore } from "./AppStore.jsx";
export { default as ForceQuit } from "./ForceQuit.jsx";
